// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: packets.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_NORTH      Direction = 0
	Direction_NORTH_EAST Direction = 1
	Direction_EAST       Direction = 2
	Direction_SOUTH_EAST Direction = 3
	Direction_SOUTH      Direction = 4
	Direction_SOUTH_WEST Direction = 5
	Direction_WEST       Direction = 6
	Direction_NORTH_WEST Direction = 7
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "NORTH",
		1: "NORTH_EAST",
		2: "EAST",
		3: "SOUTH_EAST",
		4: "SOUTH",
		5: "SOUTH_WEST",
		6: "WEST",
		7: "NORTH_WEST",
	}
	Direction_value = map[string]int32{
		"NORTH":      0,
		"NORTH_EAST": 1,
		"EAST":       2,
		"SOUTH_EAST": 3,
		"SOUTH":      4,
		"SOUTH_WEST": 5,
		"WEST":       6,
		"NORTH_WEST": 7,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

type RoomID int32

const (
	RoomID_NONE RoomID = 0
	RoomID_TOWN RoomID = 1
)

// Enum value maps for RoomID.
var (
	RoomID_name = map[int32]string{
		0: "NONE",
		1: "TOWN",
	}
	RoomID_value = map[string]int32{
		"NONE": 0,
		"TOWN": 1,
	}
)

func (x RoomID) Enum() *RoomID {
	p := new(RoomID)
	*p = x
	return p
}

func (x RoomID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomID) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[1].Descriptor()
}

func (RoomID) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[1]
}

func (x RoomID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomID.Descriptor instead.
func (RoomID) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

// Performing actions in the room
type ActionType int32

const (
	ActionType_IDLE    ActionType = 0
	ActionType_DANCING ActionType = 1
	ActionType_SITTING ActionType = 2
	ActionType_MOVING  ActionType = 3
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "IDLE",
		1: "DANCING",
		2: "SITTING",
		3: "MOVING",
	}
	ActionType_value = map[string]int32{
		"IDLE":    0,
		"DANCING": 1,
		"SITTING": 2,
		"MOVING":  3,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[2].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[2]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

// Messages
type MessageType int32

const (
	MessageType_LOGIN            MessageType = 0
	MessageType_JOIN_ROOM        MessageType = 1
	MessageType_JOINED_ROOM      MessageType = 2
	MessageType_LEFT_ROOM        MessageType = 3
	MessageType_SEND_MESSAGE     MessageType = 4
	MessageType_RECEIVED_MESSAGE MessageType = 5
	MessageType_BEGIN_ACTION     MessageType = 6
	MessageType_RECEIVED_ACTION  MessageType = 7
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "LOGIN",
		1: "JOIN_ROOM",
		2: "JOINED_ROOM",
		3: "LEFT_ROOM",
		4: "SEND_MESSAGE",
		5: "RECEIVED_MESSAGE",
		6: "BEGIN_ACTION",
		7: "RECEIVED_ACTION",
	}
	MessageType_value = map[string]int32{
		"LOGIN":            0,
		"JOIN_ROOM":        1,
		"JOINED_ROOM":      2,
		"LEFT_ROOM":        3,
		"SEND_MESSAGE":     4,
		"RECEIVED_MESSAGE": 5,
		"BEGIN_ACTION":     6,
		"RECEIVED_ACTION":  7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_packets_proto_enumTypes[3].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_packets_proto_enumTypes[3]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

// Useful types
type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Logging in on the server
// User does not need to know their own user id as the server manages that for them
type Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Login) Reset() {
	*x = Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

func (x *Login) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Joining rooms
type JoinRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID   RoomID    `protobuf:"varint,1,opt,name=roomID,proto3,enum=packets.RoomID" json:"roomID,omitempty"`
	Position *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *JoinRoom) Reset() {
	*x = JoinRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoom) ProtoMessage() {}

func (x *JoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoom.ProtoReflect.Descriptor instead.
func (*JoinRoom) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRoom) GetRoomID() RoomID {
	if x != nil {
		return x.RoomID
	}
	return RoomID_NONE
}

func (x *JoinRoom) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type JoinedRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string    `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	UserID   uint64    `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	RoomID   RoomID    `protobuf:"varint,3,opt,name=roomID,proto3,enum=packets.RoomID" json:"roomID,omitempty"`
	Position *Position `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *JoinedRoom) Reset() {
	*x = JoinedRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinedRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinedRoom) ProtoMessage() {}

func (x *JoinedRoom) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinedRoom.ProtoReflect.Descriptor instead.
func (*JoinedRoom) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

func (x *JoinedRoom) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *JoinedRoom) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *JoinedRoom) GetRoomID() RoomID {
	if x != nil {
		return x.RoomID
	}
	return RoomID_NONE
}

func (x *JoinedRoom) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

// Sent automatically when you move to another room or exit the game.
// A user can only be in one room at a time, so it is just sent to everyone who is currently in that room.
type LeftRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	RoomID RoomID `protobuf:"varint,2,opt,name=roomID,proto3,enum=packets.RoomID" json:"roomID,omitempty"`
}

func (x *LeftRoom) Reset() {
	*x = LeftRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeftRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeftRoom) ProtoMessage() {}

func (x *LeftRoom) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeftRoom.ProtoReflect.Descriptor instead.
func (*LeftRoom) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{4}
}

func (x *LeftRoom) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *LeftRoom) GetRoomID() RoomID {
	if x != nil {
		return x.RoomID
	}
	return RoomID_NONE
}

// Chat messages
type SendMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *SendMessage) Reset() {
	*x = SendMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessage) ProtoMessage() {}

func (x *SendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessage.ProtoReflect.Descriptor instead.
func (*SendMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ReceivedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID  uint64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	RoomID  RoomID `protobuf:"varint,3,opt,name=roomID,proto3,enum=packets.RoomID" json:"roomID,omitempty"`
}

func (x *ReceivedMessage) Reset() {
	*x = ReceivedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceivedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivedMessage) ProtoMessage() {}

func (x *ReceivedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivedMessage.ProtoReflect.Descriptor instead.
func (*ReceivedMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{6}
}

func (x *ReceivedMessage) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ReceivedMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReceivedMessage) GetRoomID() RoomID {
	if x != nil {
		return x.RoomID
	}
	return RoomID_NONE
}

type BeginAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActionType ActionType `protobuf:"varint,1,opt,name=actionType,proto3,enum=packets.ActionType" json:"actionType,omitempty"`
	// Types that are assignable to ActionData:
	//
	//	*BeginAction_Position
	//	*BeginAction_Direction
	ActionData isBeginAction_ActionData `protobuf_oneof:"ActionData"`
}

func (x *BeginAction) Reset() {
	*x = BeginAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeginAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginAction) ProtoMessage() {}

func (x *BeginAction) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginAction.ProtoReflect.Descriptor instead.
func (*BeginAction) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{7}
}

func (x *BeginAction) GetActionType() ActionType {
	if x != nil {
		return x.ActionType
	}
	return ActionType_IDLE
}

func (m *BeginAction) GetActionData() isBeginAction_ActionData {
	if m != nil {
		return m.ActionData
	}
	return nil
}

func (x *BeginAction) GetPosition() *Position {
	if x, ok := x.GetActionData().(*BeginAction_Position); ok {
		return x.Position
	}
	return nil
}

func (x *BeginAction) GetDirection() Direction {
	if x, ok := x.GetActionData().(*BeginAction_Direction); ok {
		return x.Direction
	}
	return Direction_NORTH
}

type isBeginAction_ActionData interface {
	isBeginAction_ActionData()
}

type BeginAction_Position struct {
	Position *Position `protobuf:"bytes,2,opt,name=position,proto3,oneof"` // Used for the move action
}

type BeginAction_Direction struct {
	Direction Direction `protobuf:"varint,3,opt,name=direction,proto3,enum=packets.Direction,oneof"` // Used for the sitting and idle actions
}

func (*BeginAction_Position) isBeginAction_ActionData() {}

func (*BeginAction_Direction) isBeginAction_ActionData() {}

type ReceivedAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID uint64       `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Action *BeginAction `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // Reusing it so I don't have to write it twice
	RoomID RoomID       `protobuf:"varint,3,opt,name=roomID,proto3,enum=packets.RoomID" json:"roomID,omitempty"`
}

func (x *ReceivedAction) Reset() {
	*x = ReceivedAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceivedAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceivedAction) ProtoMessage() {}

func (x *ReceivedAction) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceivedAction.ProtoReflect.Descriptor instead.
func (*ReceivedAction) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{8}
}

func (x *ReceivedAction) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ReceivedAction) GetAction() *BeginAction {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ReceivedAction) GetRoomID() RoomID {
	if x != nil {
		return x.RoomID
	}
	return RoomID_NONE
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=packets.MessageType" json:"messageType,omitempty"`
	// Types that are assignable to MessageData:
	//
	//	*Message_Login
	//	*Message_JoinRoom
	//	*Message_JoinedRoom
	//	*Message_LeftRoom
	//	*Message_SendMessage
	//	*Message_ReceivedMessage
	//	*Message_BeginAction
	//	*Message_ReceivedAction
	MessageData isMessage_MessageData `protobuf_oneof:"MessageData"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{9}
}

func (x *Message) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_LOGIN
}

func (m *Message) GetMessageData() isMessage_MessageData {
	if m != nil {
		return m.MessageData
	}
	return nil
}

func (x *Message) GetLogin() *Login {
	if x, ok := x.GetMessageData().(*Message_Login); ok {
		return x.Login
	}
	return nil
}

func (x *Message) GetJoinRoom() *JoinRoom {
	if x, ok := x.GetMessageData().(*Message_JoinRoom); ok {
		return x.JoinRoom
	}
	return nil
}

func (x *Message) GetJoinedRoom() *JoinedRoom {
	if x, ok := x.GetMessageData().(*Message_JoinedRoom); ok {
		return x.JoinedRoom
	}
	return nil
}

func (x *Message) GetLeftRoom() *LeftRoom {
	if x, ok := x.GetMessageData().(*Message_LeftRoom); ok {
		return x.LeftRoom
	}
	return nil
}

func (x *Message) GetSendMessage() *SendMessage {
	if x, ok := x.GetMessageData().(*Message_SendMessage); ok {
		return x.SendMessage
	}
	return nil
}

func (x *Message) GetReceivedMessage() *ReceivedMessage {
	if x, ok := x.GetMessageData().(*Message_ReceivedMessage); ok {
		return x.ReceivedMessage
	}
	return nil
}

func (x *Message) GetBeginAction() *BeginAction {
	if x, ok := x.GetMessageData().(*Message_BeginAction); ok {
		return x.BeginAction
	}
	return nil
}

func (x *Message) GetReceivedAction() *ReceivedAction {
	if x, ok := x.GetMessageData().(*Message_ReceivedAction); ok {
		return x.ReceivedAction
	}
	return nil
}

type isMessage_MessageData interface {
	isMessage_MessageData()
}

type Message_Login struct {
	Login *Login `protobuf:"bytes,2,opt,name=login,proto3,oneof"`
}

type Message_JoinRoom struct {
	JoinRoom *JoinRoom `protobuf:"bytes,3,opt,name=joinRoom,proto3,oneof"`
}

type Message_JoinedRoom struct {
	JoinedRoom *JoinedRoom `protobuf:"bytes,4,opt,name=joinedRoom,proto3,oneof"`
}

type Message_LeftRoom struct {
	LeftRoom *LeftRoom `protobuf:"bytes,5,opt,name=leftRoom,proto3,oneof"`
}

type Message_SendMessage struct {
	SendMessage *SendMessage `protobuf:"bytes,6,opt,name=sendMessage,proto3,oneof"`
}

type Message_ReceivedMessage struct {
	ReceivedMessage *ReceivedMessage `protobuf:"bytes,7,opt,name=receivedMessage,proto3,oneof"`
}

type Message_BeginAction struct {
	BeginAction *BeginAction `protobuf:"bytes,8,opt,name=beginAction,proto3,oneof"`
}

type Message_ReceivedAction struct {
	ReceivedAction *ReceivedAction `protobuf:"bytes,9,opt,name=receivedAction,proto3,oneof"`
}

func (*Message_Login) isMessage_MessageData() {}

func (*Message_JoinRoom) isMessage_MessageData() {}

func (*Message_JoinedRoom) isMessage_MessageData() {}

func (*Message_LeftRoom) isMessage_MessageData() {}

func (*Message_SendMessage) isMessage_MessageData() {}

func (*Message_ReceivedMessage) isMessage_MessageData() {}

func (*Message_BeginAction) isMessage_MessageData() {}

func (*Message_ReceivedAction) isMessage_MessageData() {}

var File_packets_proto protoreflect.FileDescriptor

var file_packets_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x22, 0x26, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79,
	0x22, 0x1b, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x62, 0x0a,
	0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x27, 0x0a, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x73, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d,
	0x49, 0x44, 0x12, 0x2d, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x98, 0x01, 0x0a, 0x0a, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x52, 0x6f, 0x6f, 0x6d,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x27, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x52,
	0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x2d, 0x0a,
	0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4b, 0x0a, 0x08,
	0x4c, 0x65, 0x66, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x27, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x44, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22, 0x27, 0x0a, 0x0b, 0x53, 0x65, 0x6e,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x22, 0x6c, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44,
	0x22, 0xb5, 0x01, 0x0a, 0x0b, 0x42, 0x65, 0x67, 0x69, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x33, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x08, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x73, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52,
	0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0c, 0x0a, 0x0a, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x22, 0x7f, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x12, 0x2c, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x42, 0x65, 0x67,
	0x69, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x27, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49,
	0x44, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x22, 0x8e, 0x04, 0x0a, 0x07, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a,
	0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x05,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x2f, 0x0a, 0x08, 0x6a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f,
	0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x48, 0x00, 0x52, 0x08, 0x6a, 0x6f,
	0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x35, 0x0a, 0x0a, 0x6a, 0x6f, 0x69, 0x6e, 0x65, 0x64,
	0x52, 0x6f, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x48,
	0x00, 0x52, 0x0a, 0x6a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x2f, 0x0a,
	0x08, 0x6c, 0x65, 0x66, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x4c, 0x65, 0x66, 0x74, 0x52, 0x6f,
	0x6f, 0x6d, 0x48, 0x00, 0x52, 0x08, 0x6c, 0x65, 0x66, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x38,
	0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x65, 0x6e,
	0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x72,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x38,
	0x0a, 0x0b, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x42, 0x65,
	0x67, 0x69, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x62, 0x65, 0x67,
	0x69, 0x6e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x41, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0e, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x64, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0d, 0x0a, 0x0b, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x2a, 0x75, 0x0a, 0x09, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x09, 0x0a, 0x05, 0x4e, 0x4f, 0x52, 0x54, 0x48,
	0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x4f, 0x52, 0x54, 0x48, 0x5f, 0x45, 0x41, 0x53, 0x54,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x41, 0x53, 0x54, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a,
	0x53, 0x4f, 0x55, 0x54, 0x48, 0x5f, 0x45, 0x41, 0x53, 0x54, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05,
	0x53, 0x4f, 0x55, 0x54, 0x48, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x4f, 0x55, 0x54, 0x48,
	0x5f, 0x57, 0x45, 0x53, 0x54, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x45, 0x53, 0x54, 0x10,
	0x06, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x4f, 0x52, 0x54, 0x48, 0x5f, 0x57, 0x45, 0x53, 0x54, 0x10,
	0x07, 0x2a, 0x1c, 0x0a, 0x06, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x2a,
	0x3c, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a,
	0x04, 0x49, 0x44, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x41, 0x4e, 0x43, 0x49,
	0x4e, 0x47, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x49, 0x54, 0x54, 0x49, 0x4e, 0x47, 0x10,
	0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x4f, 0x56, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x2a, 0x96, 0x01,
	0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a,
	0x05, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4a, 0x4f, 0x49, 0x4e,
	0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4a, 0x4f, 0x49, 0x4e, 0x45,
	0x44, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4c, 0x45, 0x46, 0x54,
	0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x4e, 0x44, 0x5f,
	0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x45, 0x43,
	0x45, 0x49, 0x56, 0x45, 0x44, 0x5f, 0x4d, 0x45, 0x53, 0x53, 0x41, 0x47, 0x45, 0x10, 0x05, 0x12,
	0x10, 0x0a, 0x0c, 0x42, 0x45, 0x47, 0x49, 0x4e, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0x06, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x43, 0x45, 0x49, 0x56, 0x45, 0x44, 0x5f, 0x41, 0x43,
	0x54, 0x49, 0x4f, 0x4e, 0x10, 0x07, 0x42, 0x14, 0x5a, 0x12, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData = file_packets_proto_rawDesc
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(file_packets_proto_rawDescData)
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_packets_proto_goTypes = []any{
	(Direction)(0),          // 0: packets.Direction
	(RoomID)(0),             // 1: packets.RoomID
	(ActionType)(0),         // 2: packets.ActionType
	(MessageType)(0),        // 3: packets.MessageType
	(*Position)(nil),        // 4: packets.Position
	(*Login)(nil),           // 5: packets.Login
	(*JoinRoom)(nil),        // 6: packets.JoinRoom
	(*JoinedRoom)(nil),      // 7: packets.JoinedRoom
	(*LeftRoom)(nil),        // 8: packets.LeftRoom
	(*SendMessage)(nil),     // 9: packets.SendMessage
	(*ReceivedMessage)(nil), // 10: packets.ReceivedMessage
	(*BeginAction)(nil),     // 11: packets.BeginAction
	(*ReceivedAction)(nil),  // 12: packets.ReceivedAction
	(*Message)(nil),         // 13: packets.Message
}
var file_packets_proto_depIdxs = []int32{
	1,  // 0: packets.JoinRoom.roomID:type_name -> packets.RoomID
	4,  // 1: packets.JoinRoom.position:type_name -> packets.Position
	1,  // 2: packets.JoinedRoom.roomID:type_name -> packets.RoomID
	4,  // 3: packets.JoinedRoom.position:type_name -> packets.Position
	1,  // 4: packets.LeftRoom.roomID:type_name -> packets.RoomID
	1,  // 5: packets.ReceivedMessage.roomID:type_name -> packets.RoomID
	2,  // 6: packets.BeginAction.actionType:type_name -> packets.ActionType
	4,  // 7: packets.BeginAction.position:type_name -> packets.Position
	0,  // 8: packets.BeginAction.direction:type_name -> packets.Direction
	11, // 9: packets.ReceivedAction.action:type_name -> packets.BeginAction
	1,  // 10: packets.ReceivedAction.roomID:type_name -> packets.RoomID
	3,  // 11: packets.Message.messageType:type_name -> packets.MessageType
	5,  // 12: packets.Message.login:type_name -> packets.Login
	6,  // 13: packets.Message.joinRoom:type_name -> packets.JoinRoom
	7,  // 14: packets.Message.joinedRoom:type_name -> packets.JoinedRoom
	8,  // 15: packets.Message.leftRoom:type_name -> packets.LeftRoom
	9,  // 16: packets.Message.sendMessage:type_name -> packets.SendMessage
	10, // 17: packets.Message.receivedMessage:type_name -> packets.ReceivedMessage
	11, // 18: packets.Message.beginAction:type_name -> packets.BeginAction
	12, // 19: packets.Message.receivedAction:type_name -> packets.ReceivedAction
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_packets_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*JoinRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*JoinedRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*LeftRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SendMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ReceivedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*BeginAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*ReceivedAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_packets_proto_msgTypes[7].OneofWrappers = []any{
		(*BeginAction_Position)(nil),
		(*BeginAction_Direction)(nil),
	}
	file_packets_proto_msgTypes[9].OneofWrappers = []any{
		(*Message_Login)(nil),
		(*Message_JoinRoom)(nil),
		(*Message_JoinedRoom)(nil),
		(*Message_LeftRoom)(nil),
		(*Message_SendMessage)(nil),
		(*Message_ReceivedMessage)(nil),
		(*Message_BeginAction)(nil),
		(*Message_ReceivedAction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_packets_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		EnumInfos:         file_packets_proto_enumTypes,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_rawDesc = nil
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
